[package]
distribution = "2201.8.6"
org = "ballerinax"
name = "zuora"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Zuora", "Subscription", "Billing", "Invoicing"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-zuora"

[build-options]
observabilityIncluded = false

[platform.java17]
graalvmCompatible = true
